pub(crate) mod build_tool;
pub mod client;
pub mod completions;
pub mod config;
pub(crate) mod docker;
pub mod download;
pub mod duration;
pub mod exec;
pub mod init;
pub(crate) mod notifications;
pub mod output;
pub mod process;
pub(crate) mod proxy;
pub mod runner;
pub(crate) mod server;
pub mod task_state;
pub(crate) mod tui;
pub(crate) mod update;
pub(crate) mod watch;

pub use config::{Config, ConfigError, Platform, TaskAutoRun};
pub use docker::stream::DockerLogReader;
pub use duration::{DurationError, parse_duration};
pub use output::{OutputError, OutputManager, ServiceWriter};
pub use runner::{Runner, RunnerError, VerboseInfo, WatchDir, WatchReport, WatchReportItem};
pub use task_state::{TaskRunInfo, TaskState, TaskStateError};
pub use tui::{TuiError, run_tui};
