pub(crate) mod build_tool;
pub mod client;
pub mod command;
pub mod completions;
pub mod config;
pub mod control;
pub mod daemon;
pub(crate) mod docker;
pub mod download;
pub mod duration;
pub(crate) mod endpoints;
pub mod exec;
pub(crate) mod facts;
pub(crate) mod gate;
pub(crate) mod globwalk;
pub mod init;
pub mod output;
pub mod param_completions;
pub mod ports;
pub mod process;
pub(crate) mod proxy;
pub mod runner;
pub(crate) mod secrets;
pub mod server;
pub mod session_summary;
pub mod signals;
pub mod state_store;
pub mod sys;
pub mod task_state;
pub(crate) mod tui;
pub(crate) mod update;
pub(crate) mod watch;
pub mod web;

pub use config::{Config, ConfigError, Platform, TaskAutoRun, TaskHeadless};
pub use docker::stream::DockerLogReader;
pub use duration::{DurationError, parse_duration};
pub use output::{LifecycleEmitter, OutputError, OutputManager, ServiceWriter};
pub use runner::{Runner, RunnerError, VerboseInfo, WatchDir, WatchReport, WatchReportItem};
pub use session_summary::SessionSummary;
pub use task_state::{TaskRunInfo, TaskStateError, TaskStateStore};
pub use tui::{TuiError, TuiMode, run_tui};
